---
name: Create and publish a Docker image to GHCR

on: push

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and publish
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          docker_compose: "docker-compose.yml"
          repo_token: "${{ secrets.GHCR_TOKEN }}"
